/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.udacityproject1.InvoiceDesign;

import com.udacityproject1.Listener.InvoicesListener;
import com.udacityproject1.Model.InvoiceHeader;
import com.udacityproject1.Model.InvoiceLine;
import com.udacityproject1.Model.InvoicesTableModel;
import com.udacityproject1.Model.ItemsTableModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author sahar
 */

public class InvoiceFrame extends javax.swing.JFrame {    
    /**
     * Creates new form InvoiceFrame
     */
    public InvoiceFrame() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        invoicesTable = new javax.swing.JTable();
        invoicesTable.getSelectionModel().addListSelectionListener(listener);
        CreateInvoiceBtn = new javax.swing.JButton();
        CreateInvoiceBtn.addActionListener(listener);
        DeleteInvoiceBtn = new javax.swing.JButton();
        DeleteInvoiceBtn.addActionListener(listener);
        InvoiceNoLabel = new javax.swing.JLabel();
        InvoiceNoValue = new javax.swing.JLabel();
        InvoiceDate = new javax.swing.JLabel();
        NameLable = new javax.swing.JLabel();
        TotalText = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        TotalValue = new javax.swing.JLabel();
        ItemsLable = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemsTable = new javax.swing.JTable();
        NewLineBtn = new javax.swing.JButton();
        NewLineBtn.addActionListener(listener);
        DeleteItemesBtn = new javax.swing.JButton();
        DeleteItemesBtn.addActionListener(listener);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        LoadMenuItem = new javax.swing.JMenuItem();
        LoadMenuItem.addActionListener(listener);
        SaveFileMenuItem = new javax.swing.JMenuItem();
        SaveFileMenuItem.addActionListener(listener);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sales Invoice Generator");

        jLabel1.setText("Invoices Table :");

        invoicesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(invoicesTable);

        CreateInvoiceBtn.setText("Create New Invoice");
        CreateInvoiceBtn.setActionCommand("CreateNewInvoice");

        DeleteInvoiceBtn.setText("Delete Invoice");
        DeleteInvoiceBtn.setActionCommand("DeleteInvoice");

        InvoiceNoLabel.setText("Invoice Number :");

        InvoiceDate.setText("Invoice Date :");

        NameLable.setText("Customer Name :");

        TotalText.setText("Invoice Total");

        ItemsLable.setText("Inovoice Items :");

        itemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(itemsTable);

        NewLineBtn.setText("Create New Line");
        NewLineBtn.setActionCommand("CreateNewLine");

        DeleteItemesBtn.setText("Delete Line");
        DeleteItemesBtn.setActionCommand("DeleteLine");

        jMenu1.setText("File");

        LoadMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK));
        LoadMenuItem.setText("Load File");
        LoadMenuItem.setActionCommand("LoadFile");
        jMenu1.add(LoadMenuItem);

        SaveFileMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        SaveFileMenuItem.setText("Save File");
        SaveFileMenuItem.setActionCommand("SaveFile");
        jMenu1.add(SaveFileMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(InvoiceNoLabel)
                                            .addComponent(InvoiceDate)
                                            .addComponent(NameLable)
                                            .addComponent(TotalText))
                                        .addGap(53, 53, 53)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dateTextField)
                                            .addComponent(nameTextField)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 6, Short.MAX_VALUE)
                                                .addComponent(InvoiceNoValue, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(505, 505, 505))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(TotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addComponent(ItemsLable)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NewLineBtn)
                                .addGap(126, 126, 126)
                                .addComponent(DeleteItemesBtn)
                                .addGap(147, 147, 147))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(CreateInvoiceBtn)
                        .addGap(139, 139, 139)
                        .addComponent(DeleteInvoiceBtn)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(InvoiceNoLabel)
                    .addComponent(InvoiceNoValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InvoiceDate)
                            .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameLable)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TotalValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TotalText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(ItemsLable)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NewLineBtn)
                            .addComponent(DeleteItemesBtn)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateInvoiceBtn)
                    .addComponent(DeleteInvoiceBtn))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    // <editor-fold defaultstate="collapsed" desc="Variables declaration"> 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateInvoiceBtn;
    private javax.swing.JButton DeleteInvoiceBtn;
    private javax.swing.JButton DeleteItemesBtn;
    private javax.swing.JLabel InvoiceDate;
    private javax.swing.JLabel InvoiceNoLabel;
    private javax.swing.JLabel InvoiceNoValue;
    private javax.swing.JLabel ItemsLable;
    private javax.swing.JMenuItem LoadMenuItem;
    private javax.swing.JLabel NameLable;
    private javax.swing.JButton NewLineBtn;
    private javax.swing.JMenuItem SaveFileMenuItem;
    private javax.swing.JLabel TotalText;
    private javax.swing.JLabel TotalValue;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JTable invoicesTable;
    private javax.swing.JTable itemsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameTextField;
    // End of variables declaration//GEN-END:variables
   
    private ArrayList<InvoiceHeader> invoicesList ;
    private ArrayList<InvoiceLine> itemLineList ;

    public void setItemLineList(ArrayList<InvoiceLine> itemLineList) {
        this.itemLineList = itemLineList;
    }
    private InvoicesTableModel invoiceHeaderTableModel;
    private ItemsTableModel invoiceLinesTableModel;
    
    
    public void setInvoicesList(ArrayList<InvoiceHeader> invoicesList) {
        this.invoicesList = invoicesList;
    }

    public ArrayList<InvoiceHeader> getInvoicesList() {
        return invoicesList;
    }

    public ArrayList<InvoiceLine> getItemLineList() {
        return itemLineList;
    }
    
    
    //Invoices Table Model get & set
    public InvoicesTableModel getInvoiceHeaderTableModel() {
        return invoiceHeaderTableModel;
    }
    public void setInvoiceHeaderTableModel(InvoicesTableModel invoiceHeaderTableModel) {
        this.invoiceHeaderTableModel = invoiceHeaderTableModel;
    }
    
    //Items Table Model get & set
    public ItemsTableModel getInvoiceLinesTableModel() {
        return invoiceLinesTableModel;
    }

    
    public void setInvoiceLinesTableModel(ItemsTableModel invoiceLinesTableModel) {
        this.invoiceLinesTableModel = invoiceLinesTableModel;
    }
    
    

// </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Lister Code">
     // Create Action Listener Object & make Action commands
     // create Lister Object
     private InvoicesListener listener = new InvoicesListener(this);
  
     public InvoicesListener getListener() {
        return listener;
      }// </editor-fold>
    
     
    // <editor-fold defaultstate="collapsed" desc="New Invoice & New Line Dialog"> 
    private CreateNewInvoiceDialog headerDialog;
    private CreateNewLineDialog lineDialog;
    // New Invoice Methods 
    public void setInvoiceHeaderDialog(CreateNewInvoiceDialog createNewInvoiceDialog) {
        this.headerDialog = createNewInvoiceDialog;
    }
    public CreateNewInvoiceDialog getInvoiceHeaderDialog() {
        return headerDialog;
    }
    
    // New Line Methods
    public void setLinenewDialog(CreateNewLineDialog lineDialog) {
        this.lineDialog = lineDialog;
    }
    public CreateNewLineDialog getLineNewDialog() {
        return lineDialog;
    }// </editor-fold>
    
    //Getter for Invoices Table
     public JTable getInvoicesTable() {
        return invoicesTable;
    }

     //Getter for Items Table
    public JTable getItemsTable() {
        return itemsTable;
    }

    public JTextField getDateTextField() {
        return dateTextField;
    }
    
    public void setDateTextField(JTextField dateTextField) {
        this.dateTextField = dateTextField;
    }
    
    

    public JTextField getNameTextField() {
        return nameTextField;
    }

    public void setNameTextField(JTextField nameTextField) {
        this.nameTextField = nameTextField;
    }

    

    public JLabel getInvoiceNoValue() {
        return InvoiceNoValue;
    }

    public void setInvoiceNoValue(JLabel InvoiceNoValue) {
        this.InvoiceNoValue = InvoiceNoValue;
    }

    public JLabel getTotalValue() {
        return TotalValue;
    }
    
    public void setTotalValue(JLabel TotalValue) {
        this.TotalValue = TotalValue;
    }

    

    
   

    
    
    
    //Get Invoice by invoice number Method
    public InvoiceHeader findInvoiceByInvNum(int invoiceNum) {
        //InvoiceHeader header = null;
        for (InvoiceHeader inv : invoicesList){
             if(inv.getInvoiceNumber() == invoiceNum){
                 return inv;
             }
        }
        return null;      
     
    }
    
}
    
    

